version: "3"
services:
  web:
    build: .
    networks:
      - network
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"
  redis:
    image: redis:alpine
    networks:
      - network
  api:
    image: rlkamradt/my-express-app:latest
    ports:
     - "3000:3000"
    networks:
      - network
networks:
  network:
